### ISSUE TITLE
Can Not Verifiy my Mail

### ISSUE THREAD

**Issue by NodoY5** [ManavvGarg/Rekol#3]
Hello @ManavvGarg,

I was trying to get registered to your service, I successfully registered and then it showed me that I need to verify my mail, I checked my mail but nothing came. What to do?

**Comment by ManavvGarg** [comment]
Hi! This service is no longer maintained as I'm currently on low resources! Sometime in the near future, there is still hope for this project. "Stay tuned" is the most suitable thing i could for now! 

Thankyou for showing interest in this project though! Very much appreciated!
